# Generated by Django 6.0.8 on 2026-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration_table',
            name='full_name',
            field=models.CharField(null=True),
        ),
    ]
