# Generated by Django 6.0.8 on 2026-09-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_registration_table_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration_table',
            name='active_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Account Suspended')], default='pending'),
        ),
    ]
