# Generated by Django 6.0.8 on 2026-09-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_registration_table_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration_table',
            name='active_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Account Suspended')], default='Approved'),
        ),
    ]
